import { useEffect, useMemo, useState } from 'react';

const icon = code => code === 0 ? '☀️' : code <= 3 ? '⛅' : code <= 48 ? '🌫️' : code <= 67 ? '🌧️' : code <= 77 ? '❄️' : code <= 86 ? '🌦️' : '⛈️';
const api = async (url, options) => { const r = await fetch(url, options); const body = r.status === 204 ? null : await r.json(); if (!r.ok) throw new Error(body?.error || 'Request failed.'); return body; };
const localDate = offset => new Date(Date.now() + offset * 86400000).toISOString().slice(0, 10);

export default function App() {
  const [query, setQuery] = useState('Toronto'); const [weather, setWeather] = useState(null);
  const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [records, setRecords] = useState([]);
  const [range, setRange] = useState({ location: 'Toronto', startDate: localDate(0), endDate: localDate(4), notes: '' });
  const [tab, setTab] = useState('weather');
  const loadRecords = () => api('/api/records').then(setRecords).catch(e => setError(e.message));
  useEffect(() => { search('Toronto'); loadRecords(); }, []);
  async function search(location = query, gps) { setLoading(true); setError(''); try { setWeather(await api(gps ? `/api/weather?lat=${gps.latitude}&lon=${gps.longitude}` : `/api/weather?location=${encodeURIComponent(location)}`)); } catch (e) { setError(e.message); } finally { setLoading(false); } }
  function currentLocation() { setError(''); if (!navigator.geolocation) return setError('Geolocation is not supported by this browser.'); navigator.geolocation.getCurrentPosition(p => search('', p.coords), e => setError(e.code === 1 ? 'Location permission was denied. Search for a city instead.' : 'Your location could not be detected.')); }
  async function save(e) { e.preventDefault(); setLoading(true); setError(''); try { await api('/api/records', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(range) }); await loadRecords(); setTab('saved'); } catch(e) { setError(e.message); } finally { setLoading(false); } }
  async function edit(r) { const notes = prompt('Update notes:', r.notes || ''); if (notes === null) return; try { await api(`/api/records/${r.id}`, { method:'PATCH', headers:{'Content-Type':'application/json'}, body:JSON.stringify({notes}) }); loadRecords(); } catch(e) { setError(e.message); } }
  async function remove(id) { if (!confirm('Delete this saved weather request?')) return; try { await api(`/api/records/${id}`, {method:'DELETE'}); loadRecords(); } catch(e) { setError(e.message); } }
  const mapUrl = useMemo(() => weather && `https://www.openstreetmap.org/?mlat=${weather.location.latitude}&mlon=${weather.location.longitude}#map=10/${weather.location.latitude}/${weather.location.longitude}`, [weather]);
  return <>
    <header><div><span className="logo">◉ WeatherWise</span><small>Weather decisions, made clearer</small></div><nav><button className={tab==='weather'?'active':''} onClick={()=>setTab('weather')}>Weather</button><button className={tab==='saved'?'active':''} onClick={()=>setTab('saved')}>Saved requests <b>{records.length}</b></button><button className={tab==='about'?'active':''} onClick={()=>setTab('about')}>About</button></nav></header>
    <main>{error && <div className="error" role="alert"><b>Couldn’t complete that request.</b><span>{error}</span><button onClick={()=>setError('')}>×</button></div>}
    {tab==='weather' && <>
      <section className="hero"><p className="eyebrow">REAL-TIME WEATHER</p><h1>Plan for what’s ahead.</h1><p>Search any city, town, postal code, or landmark—or use your current location.</p><form onSubmit={e=>{e.preventDefault();search();}}><input aria-label="Location" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Toronto, M5V, CN Tower…"/><button disabled={loading}>{loading?'Loading…':'Search'}</button><button type="button" className="secondary" onClick={currentLocation}>⌖ Use my location</button></form></section>
      {weather && <><section className="current"><div><p>NOW IN {weather.location.name.toUpperCase()}</p><h2>{Math.round(weather.current.temperature_2m)}°</h2><strong>{icon(weather.current.weather_code)} {weather.current.condition}</strong><span>Feels like {Math.round(weather.current.apparent_temperature)}°C</span></div><dl><div><dt>Humidity</dt><dd>{weather.current.relative_humidity_2m}%</dd></div><div><dt>Wind</dt><dd>{weather.current.wind_speed_10m} km/h</dd></div><div><dt>Precipitation</dt><dd>{weather.current.precipitation} mm</dd></div><div><dt>Coordinates</dt><dd>{weather.location.latitude.toFixed(2)}, {weather.location.longitude.toFixed(2)}</dd></div></dl></section>
      <section><div className="sectionTitle"><div><p className="eyebrow">5-DAY OUTLOOK</p><h2>Forecast</h2></div><a href={mapUrl} target="_blank">View on OpenStreetMap ↗</a></div><div className="forecast">{weather.daily.slice(0,5).map((d,i)=><article key={d.date}><b>{i===0?'Today':new Date(`${d.date}T12:00`).toLocaleDateString(undefined,{weekday:'short'})}</b><span className="weatherIcon">{icon(d.code)}</span><strong>{Math.round(d.max)}° <em>{Math.round(d.min)}°</em></strong><small>{d.condition}</small><small>💧 {d.precipitationChance ?? 0}% · UV {d.uvIndex}</small></article>)}</div></section>
      <section className="save"><div><p className="eyebrow">SAVE A FORECAST</p><h2>Choose a date range</h2><p>Validate a location and future range, retrieve its forecast, and store it in SQLite.</p></div><form onSubmit={save}><label>Location<input required value={range.location} onChange={e=>setRange({...range,location:e.target.value})}/></label><label>Start date<input type="date" required min={localDate(0)} max={localDate(15)} value={range.startDate} onChange={e=>setRange({...range,startDate:e.target.value})}/></label><label>End date<input type="date" required min={range.startDate} max={localDate(15)} value={range.endDate} onChange={e=>setRange({...range,endDate:e.target.value})}/></label><label className="wide">Notes (editable)<input maxLength="300" value={range.notes} onChange={e=>setRange({...range,notes:e.target.value})} placeholder="Packing reminder, trip name…"/></label><button disabled={loading}>Save request</button></form></section></>}
    </>}
    {tab==='saved' && <section><div className="sectionTitle"><div><p className="eyebrow">SQLITE PERSISTENCE</p><h1>Saved weather requests</h1></div><div><a className="button" href="/api/export.csv">Export CSV</a> <a className="button secondary" href="/api/export.json">Export JSON</a></div></div>{records.length===0?<p className="empty">No requests saved yet.</p>:<div className="tableWrap"><table><thead><tr><th>Location</th><th>Date range</th><th>Notes</th><th>Saved</th><th>Actions</th></tr></thead><tbody>{records.map(r=><tr key={r.id}><td><b>{r.location}</b><small>{r.latitude.toFixed(2)}, {r.longitude.toFixed(2)}</small></td><td>{r.startDate}<br/>to {r.endDate}</td><td>{r.notes||'—'}</td><td>{new Date(r.createdAt).toLocaleString()}</td><td><button className="link" onClick={()=>edit(r)}>Edit</button><button className="link danger" onClick={()=>remove(r.id)}>Delete</button></td></tr>)}</tbody></table></div>}</section>}
    {tab==='about' && <section className="about"><p className="eyebrow">ABOUT THE PROJECT</p><h1>Built by Rifat Chowdhury</h1><p>WeatherWise is a full-stack technical assessment demonstrating responsive React UI, external API integration, RESTful endpoints, validation, SQLite CRUD operations, graceful error handling, and data export.</p><h2>Product Manager Accelerator</h2><p>Product Manager Accelerator is a professional development community focused on helping people grow product-management skills through practical learning, mentorship, and career support.</p><p><a href="https://www.linkedin.com/company/product-manager-accelerator/" target="_blank">Visit Product Manager Accelerator on LinkedIn ↗</a></p><h2>Data sources</h2><p>Weather and geocoding: Open-Meteo. Maps: OpenStreetMap. No API key is required.</p></section>}
    </main><footer><span>WeatherWise · Rifat Chowdhury</span><span>Data from Open-Meteo · Maps from OpenStreetMap</span></footer>
  </>;
}
